### ISSUE TITLE
Improve Punchcard user onboarding

### ISSUE THREAD

**Issue by Birowsky** [punchcard/punchcard#103]
I'm starting to migrate a little Serverless app that I have to Punchcard, and report my experience along the way. It's a small app, and based on how it goes, I'll be doing the same for a different one that I have in production with a shitload of resources.

Some of the things I notice might just require better documentation, some might end up being feature requests. Whatever it ends up being, I'd just love to find a way to make this tool be my base infrastructure builder.

I'm starting here with a couple of things I noticed about dynamo with Punchcard's API.

1. How do I declare secondary global indexes?
2. How is the pattern of multiple record types per table handled?
3. If there is something missing in the Punchcard abstractions, can we fall down to the basic CDK constructs, like it's the case with the Serverless Framework?

I'm trying to migrate this table:
```
    RestaurantTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurant
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: byUserId
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: avgRating
            AttributeType: N
          - AttributeName: starCount
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: groupByStarCount
            KeySchema:
              - AttributeName: starCount
                KeyType: HASH
              - AttributeName: avgRating
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: groupByOwner
            KeySchema:
              - AttributeName: byUserId
                KeyType: HASH
              - AttributeName: avgRating
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: groupByStatus
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: avgRating
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
```
